name: CI
on:
  push:
    branches:
      - '**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt --no-cache-dir
      - name: Unittest
        run: python -m unittest src/tests/test_server.py

  push-to-dockerhub:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      REPO_NAME: python_flask_img
      COMMIT_ID: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code
    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:$COMMIT_ID
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:latest
  
  deploy-to-k8s-cluster:
    needs: [build-and-test,push-to-dockerhub]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Create kube config
      run: |
        mkdir -p $HOME/.kube/
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
    - name: Try the cluster
      run: minikube kubectl -- get pods -A
    - name: Apply the deployment YAML
      run: minikube kubectl -- apply -f kubernetes/deployments/deployment.yaml
    # - name: Apply the service YAML
    #   run: minikube kubectl -- apply -f kubernetes/services/service.yaml
    # - name: Apply the monitor YAML
    #   run: minikube kubectl -- apply -f kubernetes/servicemonitors/monitor.yaml
