name: CI
on:
  push:
    branches:
      - '**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel pytest flake8 conan
          pip install -r src/requirements.txt --no-cache-dir
      - name: Unittest
        run: python -m unittest src/tests/test_server.py 